name: Run Kubernetes

on:
  workflow_call:

jobs:
  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - run: git clone https://github.com/brunobucci/soat7grupo5-infra

    - name: Show AWS CLI Configuration
      run: aws configure list
           
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1
 
    - name: Terraform Init
      run: terraform -chdir=soat7grupo5-infra/env/prod init 

    - name: Terraform Validate
      run: terraform -chdir=soat7grupo5-infra/env/prod validate

    - name: Terraform Plan
      run: terraform -chdir=soat7grupo5-infra/env/prod plan

    - name: Terraform Apply
      run: terraform -chdir=soat7grupo5-infra/env/prod apply -auto-approve 
  
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3
      
    - name: Verificando identidade da AWS
      run: aws sts get-caller-identity

    - name: Update kube config
      run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.AWS_EKS_CLUSTER_NAME }}

    - name: Verificando configuração do kubeconfig
      run: cat ~/.kube/config
      
    - name: Verificando configuração do kubectl
      run: kubectl config view

    - name: Autenticação baseada no comando get-token
      run: aws eks get-token --cluster-name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment/deploy.yaml 
        kubectl apply -f deployment/pod_service.yaml 
        kubectl apply -f deployment/hpa.yaml 
        kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml


    - name: Criando configMap da aplicação
      run: kubectl apply -f soat7grupo5-infra/kubernets/api-configmap.yaml

    - name: Criando Deployment da aplicação
      run: kubectl apply -f soat7grupo5-infra/kubernets/api-deployment.yaml

    - name: Criando SVC da aplicação
      run: kubectl apply -f soat7grupo5-infra/kubernets/api-svc.yaml

    - name: Criando HPA da aplicação
      run: kubectl apply -f soat7grupo5-infra/kubernets/api-hpa.yaml

    - name: Criando Kube Metrics aplicação
      run: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

    - name: Alterando a imagem da APP
      run: kubectl set image deployment/soat7grupo5-api api-container=${{ vars.DOCKER_IMAGE_NAME }}:${{ vars.DOCKER_IMAGE_VERSION }}
